label: Buttons
status: ready

variants:
  - name: primary
    context:
      category: primary
      label: Primary buttons
      classes: 'usa-button'

  - name: secondary
    context:
      category: secondary
      label: Secondary buttons
      classes: 'usa-button-secondary'

  - name: secondary-inverse
    context:
      category: secondary-inverse
      label: Secondary inverse buttons
      classes: 'usa-button-secondary-inverse'
    notes: 'This will be deprecated in 2.0'

  - name: aqua
    context:
      category: alternate
      label: Aqua buttons
      classes: 'usa-button-primary-alt'

  - name: gray
    context:
      category: alternate
      label: Gray buttons
      classes: 'usa-button-gray'

  - name: red
    context:
      category: alternate
      label: Red buttons
      classes: 'usa-button-red'

  - name: big
    context:
      category: 'big'
      label: Big button
      classes: 'usa-button-big'

  - name: unstyled-primary
    context:
      category: 'unstyled-primary'
      label: Unstyled primary button
      classes: 'usa-button usa-button-unstyled'

  - name: unstyled-aqua
    context:
      category: 'unstyled-aqua'
      label: Unstyled aqua button
      classes: 'usa-button-primary-alt usa-button-unstyled'

  - name: unstyled-gray
    context:
      category: 'unstyled-gray'
      label: Unstyled gray button
      classes: 'usa-button-gray usa-button-unstyled'

  - name: unstyled-red
    context:
      category: 'unstyled-red'
      label: Unstyled red button
      classes: 'usa-button-red usa-button-unstyled'
